=== ouya-saviors/ouya-game-data/ouya-game.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://cweiske.de/ouya-game.schema.json",
    "title": "OUYA game metadata",
    "description": "Game data importable in OUYA API servers.",
    "type": "object",

    "required": [
        "packageName",
        "title",
        "releases",
        "discover",
        "media",
        "developer"
    ],
    "additionalProperties": false,
    "properties": {
        "packageName": {
            "description": "Java package names",
            "type": "string",
            "examples": [
                "com.vendor.gamename"
            ]
        },

        "title": {
            "description": "Game name",
            "type": "string"
        },

        "description": {
            "description": "Text describing the game. Newlines (CRLF) allowed",
            "type": "string"
        },

        "blockedInWebText": {
            "description": "Text describing why the game data are not visible in the web",
            "type": "string"
        },

        "players": {
            "description": "How many players can play this game at the same time?",
            "type": "array",
            "items": {
                "type": "number",
                "minimum": 1
            }
        },

        "genres": {
            "description": "Categories",
            "type": "array",
            "items": {
                "type": "string",
                "uniqueItems": true,
                "enum": [
                    "Adventure",
                    "App",
                    "Arcade/Pinball",
                    "Card/Casino",
                    "Dual Stick",
                    "Entertainment",
                    "Exclusive",
                    "Fight!",
                    "FPS/Shooter",
                    "Kids List",
                    "Meditative",
                    "Multiplayer",
                    "Music",
                    "Platformer",
                    "Puzzle/Trivia",
                    "Racing",
                    "Retro",
                    "Role-Playing",
                    "Short on Time?",
                    "Sim/Strategy",
                    "Sports",
                    "Utility",
                    "Video",
                    "VIP Room",

                    "Emulator",
                    "2019 GameJam",
                    "2020 GameJam",
                    "2020 Winter GameJam",
                    "2021 Anniversary GameJam",
                    "2021 Winter GameJam",
                    "2022 Winter GameJam",
                    "2023 Anniversary GameJam",
                    "2024 Anniversary GameJam",
                    "2025 Winter GameJam",

                    "Launcher",
                    "Open Source",
                    "PlayJam GameStick",
                    "Repackaged",
                    "Tutorials",
                    "Unlocked"
                ]
            }
        },

        "languages": {
            "description": "Language of text/audio content (ISO 639-1)",
            "type": "array",
            "items": {
                "type": "string",
                "uniqueItems": true,
                "enum": [
                    "cs",
                    "da",
                    "de",
                    "el",
                    "en",
                    "eo",
                    "es",
                    "fi",
                    "fr",
                    "hu",
                    "it",
                    "ja",
                    "ko",
                    "nl",
                    "no",
                    "pl",
                    "pt",
                    "ru",
                    "sr",
                    "sv",
                    "th",
                    "tk",
                    "uk",
                    "zh"
                ]
            }
        },

        "releases": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "name",
                    "versionCode",
                    "uuid",
                    "date",
                    "url",
                    "size",
                    "md5sum"
                ],
                "additionalProperties": false,
                "properties": {

                    "broken": {
                        "description": "If the download URL does not work anymore",
                        "type": "boolean",
                        "default": false
                    },

                    "name": {
                        "description": "Human readable version number",
                        "type": "string",
                        "examples": [
                            "1.6"
                        ]
                    },

                    "versionCode": {
                        "description": "APK-internal version code. Run \"aapt dump badging file.apk\", field \"versionCode\"",
                        "type": ["number", "null"]
                    },

                    "uuid": {
                        "description": "Unique ID for the release. Use uuid-gen to get one",
                        "type": "string"
                    },

                    "date": {
                        "description": "When the version has been released",
                        "type": "string",
                        "format": "date|datetime"
                    },

                    "url": {
                        "description": ".apk download link",
                        "type": "string",
                        "format": "url",
                        "pattern": "^(?!https://.*\\.cweiske\\.de)"
                    },

                    "size": {
                        "description": "File size in bytes",
                        "type": "number",
                        "minimum": 1
                    },

                    "md5sum": {
                        "description": "MD5 hash of the .apk file contents",
                        "type": ["string", "null"],
                        "default": null
                    },

                    "publicSize": {
                        "description": "FIXME",
                        "type": "number"
                    },

                    "nativeSize": {
                        "description": "FIXME",
                        "type": "number"
                    },

                    "cert_fingerprint": {
                        "description": "A SHA256 format fingerprint of the signing certificate that was used for this APK. Allows for authorization tracking.",
                        "type": "string",
                        "minLength": 95,
                        "maxLength": 95,
                        "pattern": "^([0-9A-F]{2}:){31}[0-9A-F]{2}$",
                        "examples": [
                            "EF:D5:B9:C0:58:C1:21:ED:97:F3:FD:89:21:12:B6:00:F6:D1:9B:C2:9B:EE:F7:47:40:0C:E0:BB:0D:25:1C:40"
                        ]
                    },

                    "cert_subject": {
                        "description": "The subject name of the signing certificate",
                        "type": "string",
                        "examples": [
                            "C = US, O = Android, CN = Android Debug",
                            "C = US, ST = CA, L = San Francisco, O = SEGA of America, OU = Mobile PD, CN = alben pedroso"
                        ]
                    },

                    "stability": {
                        "description": "What quality of a release this is",
                        "default": "stability",
                        "type": "string",
                        "enum": [
                            "alpha",
                            "beta",
                            "stable"
                        ]
                    }
                }
            }
        },

        "discover": {
            "description": "Main game image. Used in the OUYA discover store. Size 732x412",
            "type": "string",
            "format": "url",
            "pattern": "^(?!https://.*\\.cweiske\\.de)"
        },

        "media": {
            "description": "Images and videos for the details and apps pages. Can be in any order. The first video is used for the app's 'video' field, all images for app's 'screenshots'. Images are sized 1280x720",
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "type",
                    "url"
                ],
                "additionalProperties": false,
                "properties": {
                    "type": {
                        "description": "Medium type: image or video",
                        "type": "string",
                        "enum": [
                            "image",
                            "video"
                        ]
                    },
                    "url": {
                        "description": "Image URL or video URL. Vimeo and Youtube URLs supported",
                        "type": "string",
                        "format": "url",
                        "pattern": "^(?!https://.*\\.cweiske\\.de)"
                    },
                    "thumb": {
                        "description": "Small preview image. Size should be 852x479.",
                        "type": "string",
                        "format": "url",
                        "pattern": "^(?!https://.*\\.cweiske\\.de)"
                    }
                }
            }
        },

        "developer": {
            "type": "object",
            "required": [
                "name"
            ],
            "additionalProperties": false,
            "properties": {

                "uuid": {
                    "description": "Unique ID for the developer",
                    "type": ["string", "null"],
                    "default": null
                },

                "name": {
                    "description": "Developer (company or person) name",
                    "type": "string"
                },

                "supportEmail": {
                    "description": "E-Mail address for support questions",
                    "type": ["string", "null"],
                    "format": "email",
                    "default": null
                },

                "alternateEmail": {
                    "description": "Alternate E-Mail address for support questions",
                    "type": ["string", "null"],
                    "format": "email",
                    "default": null
                },

                "website": {
                    "description": "Developer website",
                    "type": ["string", "null"],
                    "format": "url",
                    "default": null
                },

                "supportPhone": {
                    "description": "Telephone number",
                    "type": ["string", "null"],
                    "default": null
                },

                "founder": {
                    "description": "If the developer was an OUYA founder",
                    "type": "boolean",
                    "default": false
                }
            }
        },

        "contentRating": {
            "description": "Which audience is this game for?",
            "type": "string",
            "enum": [
                "Everyone",
                "9+",
                "12+",
                "17+"
            ]
        },

        "website": {
            "description": "Game website",
            "type": ["string", "null"],
            "format": "url"
        },

        "firstPublishedAt": {
            "description": "When the game has first been published to the world",
            "type": ["string", "null"],
            "format": "date|date-time",
            "default": null
        },

        "inAppPurchases": {
            "description": "If you can buy things in the game",
            "type": "boolean",
            "default": false
        },

        "overview": {
            "description": "FIXME",
            "type": ["string", "null"],
            "default": null
        },

        "premium": {
            "description": "The game has no demo but has to be bought before playing it",
            "type": "boolean",
            "default": false
        },

        "rating": {
            "type": "object",
            "additionalProperties": false,
            "properties": {

                "likeCount": {
                    "description": "Number of likes this game has",
                    "type": "number",
                    "minimum": 0,
                    "default": 0
                },

                "average": {
                    "description": "Average rating for this game",
                    "type": "number",
                    "minimum": 0,
                    "maximum": 5,
                    "default": 0
                },

                "count": {
                    "description": "Number of ratings",
                    "type": "number",
                    "minimum": 0,
                    "default": 0
                }
            }
        },

        "products": {
            "description": "Items that could be bought via the discover store",
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "identifier",
                    "name",
                    "localPrice",
                    "originalPrice",
                    "currency"
                ],
                "additionalProperties": false,
                "properties": {

                    "promoted": {
                        "description": "If this product is visible in the ouya discover store",
                        "type": "boolean"
                    },

                    "type": {
                        "description": "Kind of product",
                        "type": "string",
                        "enum": ["entitlement", "consumable", "subscription"],
                        "default": "entitlement"
                    },

                    "identifier": {
                        "description": "Internal key",
                        "type": "string",
                        "examples": [
                            "full_version"
                        ]
                    },

                    "name": {
                        "description": "Human readable name",
                        "type": "string",
                        "examples": [
                            "Unlock full game"
                        ]
                    },

                    "description": {
                        "description": "Explanation of the features you will buy",
                        "type": ["string", "null"],
                        "default": null
                    },

                    "localPrice": {
                        "description": "Current price (maybe discounted)",
                        "type": "number"
                    },

                    "originalPrice": {
                        "description": "Previous price",
                        "type": "number"
                    },

                    "currency": {
                        "description": "Three-letter currency code, depending on the player that was logged in",
                        "type": "string",
                        "enum": ["EUR", "USD"]
                    }
                }
            }
        },

        "relationships": {
            "type": "object",
            "description": "Links to other OUYA applications",
            "additionalProperties": false,
            "properties": {
                "fixed": {
                    "type": "string",
                    "description": "Package name of fixed application (if this here has a bug)"
                },
                "launcher": {
                    "type": "string",
                    "description": "Package name of app that starts this one (for PlayJam GameStick games)"
                },
                "unlocked": {
                    "type": "string",
                    "description": "Package name of unlocked application (full version if this is the demo)"
                },
                "original": {
                    "type": "string",
                    "description": "Package name of original application (demo version if this is the unlocked version, unmodified GameStick game if this is the launcher)"
                }
            }
        },

        "notes": {
            "description": "Technical notes on the game, e.g. how to get it working or which controllers work.",
            "type": "string"
        }
    }
}

=== ouya-saviors/ouya-game-data/classic/com.keeplay.december21st.json
{
    "packageName": "com.keeplay.december21st",
    "title": "December 21st",
    "description": "Save the world solving enigmatic Mayan puzzles in this challenging Sokoban style game!\r\n\r\nA long time ago, somewhere in the continent of America...\r\n\r\nThe Mayans discovered that a meteor was going to collide with the Earth on December 21st, 2012.\r\nHaving predicted the end of the world on that day, they have developed a way to destroy the meteor hours before the collision, when the meteor was within reach of their invention.\r\nTherefore, a powerful shaman offered himself to be petrified and awake one day before the end of the world, when he would activate the device to destroy the meteor....\r\n\r\nThat day has come, our hero has got 24 hours to save the world...\r\n\r\nFEATURES\r\n\r\n* 100 Increasingly Difficult Levels\r\n* Many Hours Of Gameplay\r\n* Levels auto-resolution\r\n* An Undo Button to Undo Your Last Move",
    "players": [
        1
    ],
    "genres": [
        "Kids List",
        "Puzzle/Trivia"
    ],
    "releases": [
        {
            "name": "1.0.1",
            "versionCode": 0,
            "uuid": "7473965b-0bf3-44a7-8572-9400a30a2b41",
            "date": "2013-09-25T11:37:16Z",
            "url": "https://archive.org/download/ouya_com.keeplay.december21st_1.0.1/December%2021st_1.0.1_com.keeplay.december21st.apk",
            "size": 55562844,
            "md5sum": null,
            "publicSize": 0,
            "nativeSize": 0
        }
    ],
    "discover": "http://ouya.cweiske.de/game-images/com.keeplay.december21st/discover",
    "media": [
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.keeplay.december21st/screenshot-1",
            "thumb": "http://ouya.cweiske.de/game-images/com.keeplay.december21st/screenshot-1-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.keeplay.december21st/screenshot-2",
            "thumb": "http://ouya.cweiske.de/game-images/com.keeplay.december21st/screenshot-2-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.keeplay.december21st/screenshot-3",
            "thumb": "http://ouya.cweiske.de/game-images/com.keeplay.december21st/screenshot-3-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.keeplay.december21st/screenshot-4",
            "thumb": "http://ouya.cweiske.de/game-images/com.keeplay.december21st/screenshot-4-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.keeplay.december21st/screenshot-5",
            "thumb": "http://ouya.cweiske.de/game-images/com.keeplay.december21st/screenshot-5-thumb"
        }
    ],
    "developer": {
        "uuid": "00000000-9fae-4885-9667-481a91244fb4",
        "name": "Keeplay Game Studios",
        "supportEmail": "development@keeplay.com",
        "supportPhone": null,
        "founder": false
    },
    "contentRating": "Everyone",
    "website": "http://www.keeplay.com",
    "firstPublishedAt": "2013-09-22T03:15:28Z",
    "inAppPurchases": true,
    "overview": "Released in September 2013 by Keeplay Game Studios.",
    "premium": false,
    "rating": {
        "likeCount": 25,
        "average": 3.28,
        "count": 29
    }
}

=== ouya-saviors/ouya-game-data/classic/air.com.impulse12.XP1728.json
{
    "packageName": "air.com.impulse12.XP1728",
    "title": "XP1728",
    "description": "An addictive puzzle game, directly inspired by SCE's original Intelligent Qube (aka Kurushi Final in Europe), the great PlayStation hit!",
    "players": [
        1
    ],
    "genres": [
        "Puzzle/Trivia"
    ],
    "releases": [
        {
            "name": "1.3.8",
            "versionCode": 0,
            "uuid": "66ef6cf1-7383-40eb-9989-f5420cd631d0",
            "date": "2013-06-26T21:15:48Z",
            "url": "https://archive.org/download/ouya_air.com.impulse12.XP1728_1.3.8/XP1728_1.3.8_air.com.impulse12.XP1728.apk",
            "size": 47487539,
            "md5sum": null,
            "publicSize": 0,
            "nativeSize": 0
        }
    ],
    "discover": "http://ouya.cweiske.de/game-images/air.com.impulse12.XP1728/discover",
    "media": [
        {
            "type": "image",
            "url": "https://archive.org/download/ouya_air.com.impulse12.XP1728_1.3.8/tCgqGnUYRk2qP093xnar.jpg",
            "thumb": "https://archive.org/download/ouya_air.com.impulse12.XP1728_1.3.8/tCgqGnUYRk2qP093xnar_thumb.jpg"
        },
        {
            "type": "image",
            "url": "https://archive.org/download/ouya_air.com.impulse12.XP1728_1.3.8/BwjZBsrLSPNtyGspigbW.jpg",
            "thumb": "https://archive.org/download/ouya_air.com.impulse12.XP1728_1.3.8/BwjZBsrLSPNtyGspigbW_thumb.jpg"
        },
        {
            "type": "image",
            "url": "https://archive.org/download/ouya_air.com.impulse12.XP1728_1.3.8/pc2yCFrQQay431ibeaxh.jpg",
            "thumb": "https://archive.org/download/ouya_air.com.impulse12.XP1728_1.3.8/pc2yCFrQQay431ibeaxh_thumb.jpg"
        },
        {
            "type": "image",
            "url": "https://archive.org/download/ouya_air.com.impulse12.XP1728_1.3.8/jMhCrtPDQ3SIuiNYrd8B.jpg",
            "thumb": "https://archive.org/download/ouya_air.com.impulse12.XP1728_1.3.8/jMhCrtPDQ3SIuiNYrd8B_thumb.jpg"
        }
    ],
    "developer": {
        "uuid": null,
        "name": "impulse12",
        "supportEmail": "contact@impulse12.com",
        "supportPhone": null,
        "founder": true
    },
    "contentRating": "Everyone",
    "website": "www.impulse12.com",
    "firstPublishedAt": "2013-06-26T21:15:48Z",
    "inAppPurchases": true,
    "overview": "Released in June 2013 by impulse12.",
    "premium": false,
    "rating": {
        "likeCount": 77,
        "average": 3.06,
        "count": 35
    }
}

=== ouya-saviors/ouya-game-data/classic/com.dotemu.anotherworld.json
{
    "packageName": "com.dotemu.anotherworld",
    "title": "Another World",
    "description": "Also known as Out Of This World™ and released across more than a dozen platforms since its 1991 debut, Another World™ has attained cult status among critics and sophisticated gamers alike for its cinematic effects in the graphics, sound and cut scenes.\r\n\r\nA CAPTIVATING ADVENTURE\r\nThe actor plays the part of Lester Knight Chaykin, a young physics researcher. While he is right in the middle of doing experiments, his laboratory is struck by lighting and completely destroyed, hurling him into another world, a world populated by humanoid creatures, where danger can spring at any moment.\r\n\r\nYou must escape from this strange civilization. You will nonetheless meet a companion who will soon become your ally and help you in this merciless fight!\r\n\r\n20th ANNIVERSARY EDITION SPECIALLY THOUGHT OUT FOR OUYA\r\n- 3 difficulty modes: Normal (easier than the original), Hard (similar to the original) and Hardcore (harder than the original)\r\n- Sound and sound effects are 100% remastered\r\n- 5 languages available (English, French, Italian, German, Spanish)\r\n\r\nMore information on:\r\nanotherworld.fr\r\nfacebook.com/another.world.official\r\nfacebook.com/dotemu \r\ntwitter.com/dotemu\r\nyoutube.com/dotemu\r\n",
    "players": [
        1
    ],
    "genres": [
        "Adventure",
        "Retro"
    ],
    "releases": [
        {
            "name": "1.1.9",
            "versionCode": 36,
            "uuid": "422b1597-a383-48c3-8d55-f0b2aaa0bd69",
            "date": "2016-09-17T09:56:05Z",
            "url": "https://archive.org/download/ouya_com.dotemu.anotherworld_1.1.9/Another%20World_1.1.9_com.dotemu.anotherworld.apk",
            "size": 73632096,
            "md5sum": "92a67d21eea4f3902d283ac89f336fa8",
            "publicSize": 69051198,
            "nativeSize": 3428800
        }
    ],
    "discover": "http://ouya.cweiske.de/game-images/com.dotemu.anotherworld/discover",
    "media": [
        {
            "type": "video",
            "url": "https://vimeo.com/87631348"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.dotemu.anotherworld/detail-1",
            "thumb": "http://ouya.cweiske.de/game-images/com.dotemu.anotherworld/detail-1-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.dotemu.anotherworld/detail-2",
            "thumb": "http://ouya.cweiske.de/game-images/com.dotemu.anotherworld/detail-2-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.dotemu.anotherworld/detail-3",
            "thumb": "http://ouya.cweiske.de/game-images/com.dotemu.anotherworld/detail-3-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.dotemu.anotherworld/detail-4",
            "thumb": "http://ouya.cweiske.de/game-images/com.dotemu.anotherworld/detail-4-thumb"
        }
    ],
    "developer": {
        "uuid": "a25ff919-ed9e-4e80-b06d-f0d53f5a367b",
        "name": "DotEmu SAS",
        "supportEmail": "dotemu@gmail.com",
        "supportPhone": null,
        "founder": true
    },
    "contentRating": "9+",
    "website": "http://www.dotemu.com",
    "firstPublishedAt": "2013-09-17T16:40:16Z",
    "inAppPurchases": true,
    "overview": "Released in September 2016 by DotEmu SAS.",
    "premium": false,
    "rating": {
        "likeCount": 565,
        "average": 4.16,
        "count": 476
    },
    "products": [
        {
            "promoted": true,
            "identifier": "anotherworld_ouya",
            "name": "Another World",
            "description": "",
            "localPrice": 4.99,
            "originalPrice": 4.99,
            "currency": "EUR"
        }
    ]
}

=== ouya-saviors/ouya-game-data/classic/dk.MoonWalkers.indiejam2014.json
{
    "packageName": "dk.MoonWalkers.indiejam2014",
    "title": "Alien Resource Battle",
    "description": "Aliens are invading Earth and battles each other for resources like nuclear waste and industrial burgers.\n\nUpdate:\nUpdated the game to a newer version of Unity and added better explosions for the dynamite boxes that push boxes around it away.",
    "players": [
        2
    ],
    "genres": [
        "Arcade/Pinball",
        "Multiplayer"
    ],
    "releases": [
        {
            "name": "1.2",
            "versionCode": 1,
            "uuid": "20a9ad29-5105-481d-b89c-7b5a8c43ee65",
            "date": "2016-01-28T10:08:43Z",
            "url": "https://archive.org/download/ouya_dk.MoonWalkers.indiejam2014_1.2/Alien%20Resource%20Battle_1.2_dk.MoonWalkers.indiejam2014.apk",
            "size": 36534110,
            "md5sum": "62f1dcf48da082afeba7636fa3a0f4ea",
            "publicSize": 151250,
            "nativeSize": 19242100
        }
    ],
    "discover": "http://ouya.cweiske.de/game-images/dk.MoonWalkers.indiejam2014/discover",
    "media": [
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/dk.MoonWalkers.indiejam2014/detail-1",
            "thumb": "http://ouya.cweiske.de/game-images/dk.MoonWalkers.indiejam2014/detail-1-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/dk.MoonWalkers.indiejam2014/detail-2",
            "thumb": "http://ouya.cweiske.de/game-images/dk.MoonWalkers.indiejam2014/detail-2-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/dk.MoonWalkers.indiejam2014/detail-3",
            "thumb": "http://ouya.cweiske.de/game-images/dk.MoonWalkers.indiejam2014/detail-3-thumb"
        }
    ],
    "developer": {
        "uuid": "00000000-2126-4bbc-8dd2-94eb25f00382",
        "name": "Dionysus.dk",
        "supportEmail": "kaspersolesen@gmail.com",
        "supportPhone": null,
        "founder": true
    },
    "contentRating": "Everyone",
    "website": "dionysus.dk",
    "firstPublishedAt": "2014-08-14T21:16:13Z",
    "inAppPurchases": false,
    "overview": "Released in January 2016 by Dionysus.dk.",
    "premium": false,
    "rating": {
        "likeCount": 0,
        "average": 2.41,
        "count": 54
    }
}
