=== ouya-saviors/ouya-game-data/ouya-game.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://cweiske.de/ouya-game.schema.json",
    "title": "OUYA game metadata",
    "description": "Game data importable in OUYA API servers.",
    "type": "object",

    "required": [
        "packageName",
        "title",
        "releases",
        "discover",
        "media",
        "developer"
    ],
    "additionalProperties": false,
    "properties": {
        "packageName": {
            "description": "Java package names",
            "type": "string",
            "examples": [
                "com.vendor.gamename"
            ]
        },

        "title": {
            "description": "Game name",
            "type": "string"
        },

        "description": {
            "description": "Text describing the game. Newlines (CRLF) allowed",
            "type": "string"
        },

        "blockedInWebText": {
            "description": "Text describing why the game data are not visible in the web",
            "type": "string"
        },

        "players": {
            "description": "How many players can play this game at the same time?",
            "type": "array",
            "items": {
                "type": "number",
                "minimum": 1
            }
        },

        "genres": {
            "description": "Categories",
            "type": "array",
            "items": {
                "type": "string",
                "uniqueItems": true,
                "enum": [
                    "Adventure",
                    "App",
                    "Arcade/Pinball",
                    "Card/Casino",
                    "Dual Stick",
                    "Entertainment",
                    "Exclusive",
                    "Fight!",
                    "FPS/Shooter",
                    "Kids List",
                    "Meditative",
                    "Multiplayer",
                    "Music",
                    "Platformer",
                    "Puzzle/Trivia",
                    "Racing",
                    "Retro",
                    "Role-Playing",
                    "Short on Time?",
                    "Sim/Strategy",
                    "Sports",
                    "Utility",
                    "Video",
                    "VIP Room",

                    "Emulator",
                    "2019 GameJam",
                    "2020 GameJam",
                    "2020 Winter GameJam",
                    "2021 Anniversary GameJam",
                    "2021 Winter GameJam",
                    "2022 Winter GameJam",
                    "2023 Anniversary GameJam",
                    "2024 Anniversary GameJam",
                    "2025 Winter GameJam",

                    "Launcher",
                    "Open Source",
                    "PlayJam GameStick",
                    "Repackaged",
                    "Tutorials",
                    "Unlocked"
                ]
            }
        },

        "languages": {
            "description": "Language of text/audio content (ISO 639-1)",
            "type": "array",
            "items": {
                "type": "string",
                "uniqueItems": true,
                "enum": [
                    "cs",
                    "da",
                    "de",
                    "el",
                    "en",
                    "eo",
                    "es",
                    "fi",
                    "fr",
                    "hu",
                    "it",
                    "ja",
                    "ko",
                    "nl",
                    "no",
                    "pl",
                    "pt",
                    "ru",
                    "sr",
                    "sv",
                    "th",
                    "tk",
                    "uk",
                    "zh"
                ]
            }
        },

        "releases": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "name",
                    "versionCode",
                    "uuid",
                    "date",
                    "url",
                    "size",
                    "md5sum"
                ],
                "additionalProperties": false,
                "properties": {

                    "broken": {
                        "description": "If the download URL does not work anymore",
                        "type": "boolean",
                        "default": false
                    },

                    "name": {
                        "description": "Human readable version number",
                        "type": "string",
                        "examples": [
                            "1.6"
                        ]
                    },

                    "versionCode": {
                        "description": "APK-internal version code. Run \"aapt dump badging file.apk\", field \"versionCode\"",
                        "type": ["number", "null"]
                    },

                    "uuid": {
                        "description": "Unique ID for the release. Use uuid-gen to get one",
                        "type": "string"
                    },

                    "date": {
                        "description": "When the version has been released",
                        "type": "string",
                        "format": "date|datetime"
                    },

                    "url": {
                        "description": ".apk download link",
                        "type": "string",
                        "format": "url",
                        "pattern": "^(?!https://.*\\.cweiske\\.de)"
                    },

                    "size": {
                        "description": "File size in bytes",
                        "type": "number",
                        "minimum": 1
                    },

                    "md5sum": {
                        "description": "MD5 hash of the .apk file contents",
                        "type": ["string", "null"],
                        "default": null
                    },

                    "publicSize": {
                        "description": "FIXME",
                        "type": "number"
                    },

                    "nativeSize": {
                        "description": "FIXME",
                        "type": "number"
                    },

                    "cert_fingerprint": {
                        "description": "A SHA256 format fingerprint of the signing certificate that was used for this APK. Allows for authorization tracking.",
                        "type": "string",
                        "minLength": 95,
                        "maxLength": 95,
                        "pattern": "^([0-9A-F]{2}:){31}[0-9A-F]{2}$",
                        "examples": [
                            "EF:D5:B9:C0:58:C1:21:ED:97:F3:FD:89:21:12:B6:00:F6:D1:9B:C2:9B:EE:F7:47:40:0C:E0:BB:0D:25:1C:40"
                        ]
                    },

                    "cert_subject": {
                        "description": "The subject name of the signing certificate",
                        "type": "string",
                        "examples": [
                            "C = US, O = Android, CN = Android Debug",
                            "C = US, ST = CA, L = San Francisco, O = SEGA of America, OU = Mobile PD, CN = alben pedroso"
                        ]
                    },

                    "stability": {
                        "description": "What quality of a release this is",
                        "default": "stability",
                        "type": "string",
                        "enum": [
                            "alpha",
                            "beta",
                            "stable"
                        ]
                    }
                }
            }
        },

        "discover": {
            "description": "Main game image. Used in the OUYA discover store. Size 732x412",
            "type": "string",
            "format": "url",
            "pattern": "^(?!https://.*\\.cweiske\\.de)"
        },

        "media": {
            "description": "Images and videos for the details and apps pages. Can be in any order. The first video is used for the app's 'video' field, all images for app's 'screenshots'. Images are sized 1280x720",
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "type",
                    "url"
                ],
                "additionalProperties": false,
                "properties": {
                    "type": {
                        "description": "Medium type: image or video",
                        "type": "string",
                        "enum": [
                            "image",
                            "video"
                        ]
                    },
                    "url": {
                        "description": "Image URL or video URL. Vimeo and Youtube URLs supported",
                        "type": "string",
                        "format": "url",
                        "pattern": "^(?!https://.*\\.cweiske\\.de)"
                    },
                    "thumb": {
                        "description": "Small preview image. Size should be 852x479.",
                        "type": "string",
                        "format": "url",
                        "pattern": "^(?!https://.*\\.cweiske\\.de)"
                    }
                }
            }
        },

        "developer": {
            "type": "object",
            "required": [
                "name"
            ],
            "additionalProperties": false,
            "properties": {

                "uuid": {
                    "description": "Unique ID for the developer",
                    "type": ["string", "null"],
                    "default": null
                },

                "name": {
                    "description": "Developer (company or person) name",
                    "type": "string"
                },

                "supportEmail": {
                    "description": "E-Mail address for support questions",
                    "type": ["string", "null"],
                    "format": "email",
                    "default": null
                },

                "alternateEmail": {
                    "description": "Alternate E-Mail address for support questions",
                    "type": ["string", "null"],
                    "format": "email",
                    "default": null
                },

                "website": {
                    "description": "Developer website",
                    "type": ["string", "null"],
                    "format": "url",
                    "default": null
                },

                "supportPhone": {
                    "description": "Telephone number",
                    "type": ["string", "null"],
                    "default": null
                },

                "founder": {
                    "description": "If the developer was an OUYA founder",
                    "type": "boolean",
                    "default": false
                }
            }
        },

        "contentRating": {
            "description": "Which audience is this game for?",
            "type": "string",
            "enum": [
                "Everyone",
                "9+",
                "12+",
                "17+"
            ]
        },

        "website": {
            "description": "Game website",
            "type": ["string", "null"],
            "format": "url"
        },

        "firstPublishedAt": {
            "description": "When the game has first been published to the world",
            "type": ["string", "null"],
            "format": "date|date-time",
            "default": null
        },

        "inAppPurchases": {
            "description": "If you can buy things in the game",
            "type": "boolean",
            "default": false
        },

        "overview": {
            "description": "FIXME",
            "type": ["string", "null"],
            "default": null
        },

        "premium": {
            "description": "The game has no demo but has to be bought before playing it",
            "type": "boolean",
            "default": false
        },

        "rating": {
            "type": "object",
            "additionalProperties": false,
            "properties": {

                "likeCount": {
                    "description": "Number of likes this game has",
                    "type": "number",
                    "minimum": 0,
                    "default": 0
                },

                "average": {
                    "description": "Average rating for this game",
                    "type": "number",
                    "minimum": 0,
                    "maximum": 5,
                    "default": 0
                },

                "count": {
                    "description": "Number of ratings",
                    "type": "number",
                    "minimum": 0,
                    "default": 0
                }
            }
        },

        "products": {
            "description": "Items that could be bought via the discover store",
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "identifier",
                    "name",
                    "localPrice",
                    "originalPrice",
                    "currency"
                ],
                "additionalProperties": false,
                "properties": {

                    "promoted": {
                        "description": "If this product is visible in the ouya discover store",
                        "type": "boolean"
                    },

                    "type": {
                        "description": "Kind of product",
                        "type": "string",
                        "enum": ["entitlement", "consumable", "subscription"],
                        "default": "entitlement"
                    },

                    "identifier": {
                        "description": "Internal key",
                        "type": "string",
                        "examples": [
                            "full_version"
                        ]
                    },

                    "name": {
                        "description": "Human readable name",
                        "type": "string",
                        "examples": [
                            "Unlock full game"
                        ]
                    },

                    "description": {
                        "description": "Explanation of the features you will buy",
                        "type": ["string", "null"],
                        "default": null
                    },

                    "localPrice": {
                        "description": "Current price (maybe discounted)",
                        "type": "number"
                    },

                    "originalPrice": {
                        "description": "Previous price",
                        "type": "number"
                    },

                    "currency": {
                        "description": "Three-letter currency code, depending on the player that was logged in",
                        "type": "string",
                        "enum": ["EUR", "USD"]
                    }
                }
            }
        },

        "relationships": {
            "type": "object",
            "description": "Links to other OUYA applications",
            "additionalProperties": false,
            "properties": {
                "fixed": {
                    "type": "string",
                    "description": "Package name of fixed application (if this here has a bug)"
                },
                "launcher": {
                    "type": "string",
                    "description": "Package name of app that starts this one (for PlayJam GameStick games)"
                },
                "unlocked": {
                    "type": "string",
                    "description": "Package name of unlocked application (full version if this is the demo)"
                },
                "original": {
                    "type": "string",
                    "description": "Package name of original application (demo version if this is the unlocked version, unmodified GameStick game if this is the launcher)"
                }
            }
        },

        "notes": {
            "description": "Technical notes on the game, e.g. how to get it working or which controllers work.",
            "type": "string"
        }
    }
}

=== ouya-saviors/ouya-game-data/classic/com.thepilltree.spacecathd.json
{
    "packageName": "com.thepilltree.spacecathd",
    "title": "SpaceCat HD",
    "description": "“Love space? Love cats? Then you’ll probably like SpaceCats. Witty touches and great attention to detail make this more than a one-play gimmick too. (8.2/10)” - Life of Android\r\n\r\n“You really should download this. The graphics are very good, the game play is both fun yet challenging as you progress and the game is all-round well polished and cool to play (4.6/5)” - AndroidTapp \r\n\r\nSpaceCat has an innovative gameplay that combines a lander with a platform game with high quality graphics.\r\n\r\nDodge walls, avoid lasers, pilot through narrow passages, catch the floating mice and more.",
    "players": [
        1
    ],
    "genres": [
        "Kids List",
        "Platformer",
        "Puzzle/Trivia",
        "Short on Time?"
    ],
    "releases": [
        {
            "name": "2.0.6",
            "versionCode": 0,
            "uuid": "2eae9f07-10bb-47a4-8ff4-be9b63d02b0c",
            "date": "2014-03-25T08:31:53Z",
            "url": "https://archive.org/download/ouya_com.thepilltree.spacecathd_2.0.6/SpaceCat%20HD_2.0.6_com.thepilltree.spacecathd.apk",
            "size": 12173635,
            "md5sum": "d702efe38be9db982bfb0e9840d23a88",
            "publicSize": 11240716,
            "nativeSize": 0
        }
    ],
    "discover": "http://ouya.cweiske.de/game-images/com.thepilltree.spacecathd/discover",
    "media": [
        {
            "type": "video",
            "url": "https://vimeo.com/90207706"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.thepilltree.spacecathd/screenshot-1",
            "thumb": "http://ouya.cweiske.de/game-images/com.thepilltree.spacecathd/screenshot-1-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.thepilltree.spacecathd/screenshot-2",
            "thumb": "http://ouya.cweiske.de/game-images/com.thepilltree.spacecathd/screenshot-2-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.thepilltree.spacecathd/screenshot-3",
            "thumb": "http://ouya.cweiske.de/game-images/com.thepilltree.spacecathd/screenshot-3-thumb"
        }
    ],
    "developer": {
        "uuid": null,
        "name": "Platty Soft",
        "supportEmail": "raul@plattysoft.com",
        "supportPhone": null,
        "founder": false
    },
    "contentRating": "9+",
    "website": "http://www.plattysoft.com/the-pill-tree/spacecat/",
    "firstPublishedAt": "2014-03-25T08:31:53Z",
    "inAppPurchases": true,
    "overview": "Released in March 2014 by Platty Soft.",
    "premium": false,
    "rating": {
        "likeCount": 56,
        "average": 3.67,
        "count": 316
    },
    "products": [
        {
            "promoted": true,
            "identifier": "full_game",
            "name": "Unlock SpaceCat HD",
            "description": "Unlocks all the levels of SpaceCat HD",
            "localPrice": 1.99,
            "originalPrice": 1.99,
            "currency": "EUR"
        }
    ]
}

=== ouya-saviors/ouya-game-data/gamestick/com.DefiantDev.SkiSafari.launcher.json
{
    "packageName": "com.DefiantDev.SkiSafari.launcher",
    "title": "Ski Safari (Launcher)",
    "description": "Welcome to Ski Safari!\r\n\r\nSki Safari is where Animals, Avalanches and Action come together to create a new casual gameplay experience.\r\n\r\nSven, as we like to call him, can use animals to aid his escape from an icey end.\r\n\r\nCompleting objectives can 'level up' Sven and increase his score multiplier. Ride animals, perform backflips and Sven will be rocketing up the highscore table with ease.",
    "players": [
        1
    ],
    "genres": [
        "PlayJam GameStick",
        "Arcade/Pinball"
    ],
    "releases": [
        {
            "name": "1.0",
            "versionCode": 1,
            "uuid": "03e8e0a6-1e4f-4580-928e-8efdd1313cf5",
            "date": "2025-11-12T17:32:58Z",
            "url": "http://ouya.cweiske.de/apks/gamestick/com.DefiantDev.SkiSafari/com.DefiantDev.SkiSafari.launcher-1.apk",
            "size": 106972,
            "md5sum": "c97633c71a8aa97a5576ae57f0500e43",
            "cert_fingerprint": "A3:81:0C:7A:E7:20:11:83:33:F6:8C:55:F4:9C:D4:14:5F:D4:A0:2E:C0:11:27:F8:CC:62:56:D6:A5:07:F4:1A",
            "cert_subject": "C=AT, OU=CEO, CN=Andreas St."
        }
    ],
    "discover": "http://ouya.cweiske.de/apks/gamestick/com.DefiantDev.SkiSafari/discover",
    "media": [
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/apks/gamestick/com.DefiantDev.SkiSafari/screen1.jpg"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/apks/gamestick/com.DefiantDev.SkiSafari/screen2.jpg"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/apks/gamestick/com.DefiantDev.SkiSafari/screen3.jpg"
        }
    ],
    "developer": {
        "uuid": "11111111-2590-4f1f-b4ad-7a3ea00edfd6",
        "name": "Andiweli"
    },
    "contentRating": "Everyone",
    "website": null,
    "firstPublishedAt": "2013-09-17",
    "inAppPurchases": false,
    "premium": true,
    "relationships": {
        "original": "com.DefiantDev.SkiSafari"
    }
}

=== ouya-saviors/ouya-game-data/classic/com.replay.festermudd1ouya.json
{
    "packageName": "com.replay.festermudd1ouya",
    "title": "Fester Mudd: Episode 1",
    "description": "Set in the Wild West, FESTER MUDD: CURSE OF THE GOLD is a three-part comic saga of exploration, reunion, and redemption...and a love letter to the classic adventure games of the 90s!\r\n\r\nRoused from a life of sloth to reunite with his long-lost brother in search of unimaginable riches, reluctant hero Fester Mudd somehow manages to be intrepid but cowardly, ambitious yet lazy, dimwitted but brilliant.\r\n\r\nIn Episode 1, Fester hits the trail to join his brother, Bud, in the downtrodden town of Loamsmouth. But when Bud is found to have mysteriously vanished, Fester realizes that the journey will be far longer and more treacherous than he bargained for...and he must enlist the aid of an experienced gunslinger to help him make his way through Indian territory to track down both his missing brother and the gold that awaits them both!\r\n\r\nBut gunslingers don't come cheap...and Fester must find a way to convince him to join him on the perilous quest.\r\n\r\nThis Episode sees Fester exploring Loamsmouth and surrounding territories. Along the way, he'll meet and deal with an assortment of Old West roughnecks, flim-flammers, and other larger-than-life characters...and give adventure game fans a huge blast from the past!\r\n\r\n★ Perfectly optimized for OUYA controller!\r\n★ Lush graphics and vivid sound effects that bring the Old West to life!\r\n★ Classic adventuring interface allowing for sophisticated interactions!\r\n★ Branching dialogues!\r\n★ Dozens of classic inventory-style puzzles!\r\n★ Overhead map for quick travel between regions!\r\n★ An original soundtrack that perfectly evokes the era of Old West and Old School Adventure Games!\r\n★ Cliffhanger ending that teases the next game in the series!\r\n★ Countless jokes, gags, and tips-of-the-hat to the golden-age adventures of Sierra and LucasArts!\r\n\r\n*Sierra Online is a Trademark of Activision Blizzard Entertainment and LucasArts is a Trademark of Disney Inc.",
    "players": [
        1
    ],
    "genres": [
        "Adventure",
        "Retro"
    ],
    "releases": [
        {
            "name": "1.0.0",
            "versionCode": 0,
            "uuid": "5a264b38-270b-4838-b205-b8469921a79c",
            "date": "2013-06-11T08:09:46Z",
            "url": "https://archive.org/download/ouya_com.replay.festermudd1ouya_1.0.0/Fester%20Mudd_1.0.0_com.replay.festermudd1ouya.apk",
            "size": 27913162,
            "md5sum": null,
            "publicSize": 0,
            "nativeSize": 0
        }
    ],
    "discover": "http://ouya.cweiske.de/game-images/com.replay.festermudd1ouya/discover",
    "media": [
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.replay.festermudd1ouya/screenshot-1",
            "thumb": "http://ouya.cweiske.de/game-images/com.replay.festermudd1ouya/screenshot-1-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.replay.festermudd1ouya/screenshot-2",
            "thumb": "http://ouya.cweiske.de/game-images/com.replay.festermudd1ouya/screenshot-2-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.replay.festermudd1ouya/screenshot-3",
            "thumb": "http://ouya.cweiske.de/game-images/com.replay.festermudd1ouya/screenshot-3-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.replay.festermudd1ouya/screenshot-4",
            "thumb": "http://ouya.cweiske.de/game-images/com.replay.festermudd1ouya/screenshot-4-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.replay.festermudd1ouya/screenshot-5",
            "thumb": "http://ouya.cweiske.de/game-images/com.replay.festermudd1ouya/screenshot-5-thumb"
        }
    ],
    "developer": {
        "uuid": null,
        "name": "Replay Games",
        "supportEmail": "support@prankentertainment.com",
        "supportPhone": null,
        "founder": false
    },
    "contentRating": "12+",
    "website": "www.festermudd.com",
    "firstPublishedAt": "2013-06-11T08:09:46Z",
    "inAppPurchases": true,
    "overview": "Released in June 2013 by Replay Games.",
    "premium": false,
    "rating": {
        "likeCount": 164,
        "average": 3.21,
        "count": 53
    }
}

=== ouya-saviors/ouya-game-data/gamestick/com.pixelbite.Repulze.json
{
    "packageName": "com.pixelbite.Repulze",
    "title": "Repulze",
    "description": "This action racer puts you in the seat of experimental Repulze hovercraft working as a test pilot for the Man. Well, the Synthetic Man is more accurate. \r\n\r\nThe Synthetics run the corporations. The corporations run the world. You are way down the food chain getting pushed around to complete their \"scientific\" challenges. But you'll show 'em.",
    "players": [
        1
    ],
    "genres": [
        "PlayJam GameStick",
        "Racing"
    ],
    "releases": [
        {
            "name": "1.0.0",
            "versionCode": 100,
            "uuid": "b441e79b-6a87-4d23-8787-24e42845a57f",
            "date": "2025-07-20T13:41:12Z",
            "url": "http://gamestick.cweiske.de/archive/gamestick_com.pixelbite.Repulze/Repulze_1.0.0_com.pixelbite.Repulze.apk",
            "size": 143661159,
            "md5sum": "88c46876ee22e4e2983b29efd41500cc",
            "cert_fingerprint": "4D:90:5E:B3:75:42:13:84:3F:F7:80:E3:24:36:38:CF:E8:62:E7:22:72:DF:71:69:55:DE:62:53:4D:E7:C5:D9",
            "cert_subject": "C=46, ST=Sweden, L=Helsingborg, O=Pixelbite AB, OU=programming, CN=Tobias"
        }
    ],
    "discover": "http://ouya.cweiske.de/apks/gamestick/com.pixelbite.Repulze/discover",
    "media": [
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/apks/gamestick/com.pixelbite.Repulze/screen1.jpg"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/apks/gamestick/com.pixelbite.Repulze/screen2.jpg"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/apks/gamestick/com.pixelbite.Repulze/screen3.jpg"
        }
    ],
    "developer": {
        "name": "Pixelbite"
    },
    "contentRating": "Everyone",
    "website": null,
    "firstPublishedAt": "2013-09-16",
    "inAppPurchases": true,
    "premium": true,
    "relationships": {
        "launcher": "com.pixelbite.Repulze.launcher"
    }
}
