=== ouya-saviors/ouya-game-data/ouya-game.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://cweiske.de/ouya-game.schema.json",
    "title": "OUYA game metadata",
    "description": "Game data importable in OUYA API servers.",
    "type": "object",

    "required": [
        "packageName",
        "title",
        "releases",
        "discover",
        "media",
        "developer"
    ],
    "additionalProperties": false,
    "properties": {
        "packageName": {
            "description": "Java package names",
            "type": "string",
            "examples": [
                "com.vendor.gamename"
            ]
        },

        "title": {
            "description": "Game name",
            "type": "string"
        },

        "description": {
            "description": "Text describing the game. Newlines (CRLF) allowed",
            "type": "string"
        },

        "blockedInWebText": {
            "description": "Text describing why the game data are not visible in the web",
            "type": "string"
        },

        "players": {
            "description": "How many players can play this game at the same time?",
            "type": "array",
            "items": {
                "type": "number",
                "minimum": 1
            }
        },

        "genres": {
            "description": "Categories",
            "type": "array",
            "items": {
                "type": "string",
                "uniqueItems": true,
                "enum": [
                    "Adventure",
                    "App",
                    "Arcade/Pinball",
                    "Card/Casino",
                    "Dual Stick",
                    "Entertainment",
                    "Exclusive",
                    "Fight!",
                    "FPS/Shooter",
                    "Kids List",
                    "Meditative",
                    "Multiplayer",
                    "Music",
                    "Platformer",
                    "Puzzle/Trivia",
                    "Racing",
                    "Retro",
                    "Role-Playing",
                    "Short on Time?",
                    "Sim/Strategy",
                    "Sports",
                    "Utility",
                    "Video",
                    "VIP Room",

                    "Emulator",
                    "2019 GameJam",
                    "2020 GameJam",
                    "2020 Winter GameJam",
                    "2021 Anniversary GameJam",
                    "2021 Winter GameJam",
                    "2022 Winter GameJam",
                    "2023 Anniversary GameJam",
                    "2024 Anniversary GameJam",
                    "2025 Winter GameJam",

                    "Launcher",
                    "Open Source",
                    "PlayJam GameStick",
                    "Repackaged",
                    "Tutorials",
                    "Unlocked"
                ]
            }
        },

        "languages": {
            "description": "Language of text/audio content (ISO 639-1)",
            "type": "array",
            "items": {
                "type": "string",
                "uniqueItems": true,
                "enum": [
                    "cs",
                    "da",
                    "de",
                    "el",
                    "en",
                    "eo",
                    "es",
                    "fi",
                    "fr",
                    "hu",
                    "it",
                    "ja",
                    "ko",
                    "nl",
                    "no",
                    "pl",
                    "pt",
                    "ru",
                    "sr",
                    "sv",
                    "th",
                    "tk",
                    "uk",
                    "zh"
                ]
            }
        },

        "releases": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "name",
                    "versionCode",
                    "uuid",
                    "date",
                    "url",
                    "size",
                    "md5sum"
                ],
                "additionalProperties": false,
                "properties": {

                    "broken": {
                        "description": "If the download URL does not work anymore",
                        "type": "boolean",
                        "default": false
                    },

                    "name": {
                        "description": "Human readable version number",
                        "type": "string",
                        "examples": [
                            "1.6"
                        ]
                    },

                    "versionCode": {
                        "description": "APK-internal version code. Run \"aapt dump badging file.apk\", field \"versionCode\"",
                        "type": ["number", "null"]
                    },

                    "uuid": {
                        "description": "Unique ID for the release. Use uuid-gen to get one",
                        "type": "string"
                    },

                    "date": {
                        "description": "When the version has been released",
                        "type": "string",
                        "format": "date|datetime"
                    },

                    "url": {
                        "description": ".apk download link",
                        "type": "string",
                        "format": "url",
                        "pattern": "^(?!https://.*\\.cweiske\\.de)"
                    },

                    "size": {
                        "description": "File size in bytes",
                        "type": "number",
                        "minimum": 1
                    },

                    "md5sum": {
                        "description": "MD5 hash of the .apk file contents",
                        "type": ["string", "null"],
                        "default": null
                    },

                    "publicSize": {
                        "description": "FIXME",
                        "type": "number"
                    },

                    "nativeSize": {
                        "description": "FIXME",
                        "type": "number"
                    },

                    "cert_fingerprint": {
                        "description": "A SHA256 format fingerprint of the signing certificate that was used for this APK. Allows for authorization tracking.",
                        "type": "string",
                        "minLength": 95,
                        "maxLength": 95,
                        "pattern": "^([0-9A-F]{2}:){31}[0-9A-F]{2}$",
                        "examples": [
                            "EF:D5:B9:C0:58:C1:21:ED:97:F3:FD:89:21:12:B6:00:F6:D1:9B:C2:9B:EE:F7:47:40:0C:E0:BB:0D:25:1C:40"
                        ]
                    },

                    "cert_subject": {
                        "description": "The subject name of the signing certificate",
                        "type": "string",
                        "examples": [
                            "C = US, O = Android, CN = Android Debug",
                            "C = US, ST = CA, L = San Francisco, O = SEGA of America, OU = Mobile PD, CN = alben pedroso"
                        ]
                    },

                    "stability": {
                        "description": "What quality of a release this is",
                        "default": "stability",
                        "type": "string",
                        "enum": [
                            "alpha",
                            "beta",
                            "stable"
                        ]
                    }
                }
            }
        },

        "discover": {
            "description": "Main game image. Used in the OUYA discover store. Size 732x412",
            "type": "string",
            "format": "url",
            "pattern": "^(?!https://.*\\.cweiske\\.de)"
        },

        "media": {
            "description": "Images and videos for the details and apps pages. Can be in any order. The first video is used for the app's 'video' field, all images for app's 'screenshots'. Images are sized 1280x720",
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "type",
                    "url"
                ],
                "additionalProperties": false,
                "properties": {
                    "type": {
                        "description": "Medium type: image or video",
                        "type": "string",
                        "enum": [
                            "image",
                            "video"
                        ]
                    },
                    "url": {
                        "description": "Image URL or video URL. Vimeo and Youtube URLs supported",
                        "type": "string",
                        "format": "url",
                        "pattern": "^(?!https://.*\\.cweiske\\.de)"
                    },
                    "thumb": {
                        "description": "Small preview image. Size should be 852x479.",
                        "type": "string",
                        "format": "url",
                        "pattern": "^(?!https://.*\\.cweiske\\.de)"
                    }
                }
            }
        },

        "developer": {
            "type": "object",
            "required": [
                "name"
            ],
            "additionalProperties": false,
            "properties": {

                "uuid": {
                    "description": "Unique ID for the developer",
                    "type": ["string", "null"],
                    "default": null
                },

                "name": {
                    "description": "Developer (company or person) name",
                    "type": "string"
                },

                "supportEmail": {
                    "description": "E-Mail address for support questions",
                    "type": ["string", "null"],
                    "format": "email",
                    "default": null
                },

                "alternateEmail": {
                    "description": "Alternate E-Mail address for support questions",
                    "type": ["string", "null"],
                    "format": "email",
                    "default": null
                },

                "website": {
                    "description": "Developer website",
                    "type": ["string", "null"],
                    "format": "url",
                    "default": null
                },

                "supportPhone": {
                    "description": "Telephone number",
                    "type": ["string", "null"],
                    "default": null
                },

                "founder": {
                    "description": "If the developer was an OUYA founder",
                    "type": "boolean",
                    "default": false
                }
            }
        },

        "contentRating": {
            "description": "Which audience is this game for?",
            "type": "string",
            "enum": [
                "Everyone",
                "9+",
                "12+",
                "17+"
            ]
        },

        "website": {
            "description": "Game website",
            "type": ["string", "null"],
            "format": "url"
        },

        "firstPublishedAt": {
            "description": "When the game has first been published to the world",
            "type": ["string", "null"],
            "format": "date|date-time",
            "default": null
        },

        "inAppPurchases": {
            "description": "If you can buy things in the game",
            "type": "boolean",
            "default": false
        },

        "overview": {
            "description": "FIXME",
            "type": ["string", "null"],
            "default": null
        },

        "premium": {
            "description": "The game has no demo but has to be bought before playing it",
            "type": "boolean",
            "default": false
        },

        "rating": {
            "type": "object",
            "additionalProperties": false,
            "properties": {

                "likeCount": {
                    "description": "Number of likes this game has",
                    "type": "number",
                    "minimum": 0,
                    "default": 0
                },

                "average": {
                    "description": "Average rating for this game",
                    "type": "number",
                    "minimum": 0,
                    "maximum": 5,
                    "default": 0
                },

                "count": {
                    "description": "Number of ratings",
                    "type": "number",
                    "minimum": 0,
                    "default": 0
                }
            }
        },

        "products": {
            "description": "Items that could be bought via the discover store",
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "identifier",
                    "name",
                    "localPrice",
                    "originalPrice",
                    "currency"
                ],
                "additionalProperties": false,
                "properties": {

                    "promoted": {
                        "description": "If this product is visible in the ouya discover store",
                        "type": "boolean"
                    },

                    "type": {
                        "description": "Kind of product",
                        "type": "string",
                        "enum": ["entitlement", "consumable", "subscription"],
                        "default": "entitlement"
                    },

                    "identifier": {
                        "description": "Internal key",
                        "type": "string",
                        "examples": [
                            "full_version"
                        ]
                    },

                    "name": {
                        "description": "Human readable name",
                        "type": "string",
                        "examples": [
                            "Unlock full game"
                        ]
                    },

                    "description": {
                        "description": "Explanation of the features you will buy",
                        "type": ["string", "null"],
                        "default": null
                    },

                    "localPrice": {
                        "description": "Current price (maybe discounted)",
                        "type": "number"
                    },

                    "originalPrice": {
                        "description": "Previous price",
                        "type": "number"
                    },

                    "currency": {
                        "description": "Three-letter currency code, depending on the player that was logged in",
                        "type": "string",
                        "enum": ["EUR", "USD"]
                    }
                }
            }
        },

        "relationships": {
            "type": "object",
            "description": "Links to other OUYA applications",
            "additionalProperties": false,
            "properties": {
                "fixed": {
                    "type": "string",
                    "description": "Package name of fixed application (if this here has a bug)"
                },
                "launcher": {
                    "type": "string",
                    "description": "Package name of app that starts this one (for PlayJam GameStick games)"
                },
                "unlocked": {
                    "type": "string",
                    "description": "Package name of unlocked application (full version if this is the demo)"
                },
                "original": {
                    "type": "string",
                    "description": "Package name of original application (demo version if this is the unlocked version, unmodified GameStick game if this is the launcher)"
                }
            }
        },

        "notes": {
            "description": "Technical notes on the game, e.g. how to get it working or which controllers work.",
            "type": "string"
        }
    }
}

=== ouya-saviors/ouya-game-data/classic/com.jackboxgames.JackboxPartyLoaderFull.json
{
    "packageName": "com.jackboxgames.JackboxPartyLoaderFull",
    "title": "The Jackbox Party Pack",
    "description": "For 1-100 players! Your phones or tablets are your controllers! The team behind YOU DON’T KNOW JACK presents FIVE guffaw-inducing party games in one pack! Games include: \n 1) The comedy trivia sensation YOU DON’T NOW JACK 2015 (1-4 players) with hundreds of all-new questions. \n 2) The hilarious bluffing game Fibbage XL (2-8 players), with 50% more questions added to the original hit game Fibbage. \n 3) The bizarre drawing game Drawful (3-8 players) - you draw right there on your phone or tablet (very little/no real skill required). \n 4) The racy-as-you-want-to-be fill-in-the-blank word game Word Spud (2-8 players). \n 5) The wacky-fact-filled Lie Swatter (1-100 players). \n\nPlayers play using their phones, tablets, or even computers as controllers – making it the perfect easy-in entertainment piece for your next game night or party. Once a game is started from the in-pack menu, players simply connect to the “jackbox.tv” web address on their device and then enter the on-screen room code to enter a game. No big mess of controllers needed! You’re gonna need more than one party for this. \n\nNote: The games included in this pack are in English only & are local multiplayer only.",
    "players": [
        1
    ],
    "genres": [
        "Multiplayer",
        "Puzzle/Trivia"
    ],
    "releases": [
        {
            "name": "1.0.6",
            "versionCode": 0,
            "uuid": "9f7e7574-c6d9-4537-94ee-c277fe373e3f",
            "date": "2017-04-11T22:58:59Z",
            "url": "https://archive.org/download/ouya_com.jackboxgames.JackboxPartyLoaderFull_1.0.6/The%20Jackbox%20Party%20Pack_1.0.6_com.jackboxgames.JackboxPartyLoaderFull.apk",
            "size": 552550272,
            "md5sum": "f26304c0507c72d31625713a3d6bd7e5",
            "publicSize": 192121932,
            "nativeSize": 8939328
        }
    ],
    "discover": "http://ouya.cweiske.de/game-images/com.jackboxgames.JackboxPartyLoaderFull/discover",
    "media": [
        {
            "type": "video",
            "url": "https://vimeo.com/117508130"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.jackboxgames.JackboxPartyLoaderFull/detail-1",
            "thumb": "http://ouya.cweiske.de/game-images/com.jackboxgames.JackboxPartyLoaderFull/detail-1-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.jackboxgames.JackboxPartyLoaderFull/detail-2",
            "thumb": "http://ouya.cweiske.de/game-images/com.jackboxgames.JackboxPartyLoaderFull/detail-2-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.jackboxgames.JackboxPartyLoaderFull/detail-3",
            "thumb": "http://ouya.cweiske.de/game-images/com.jackboxgames.JackboxPartyLoaderFull/detail-3-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.jackboxgames.JackboxPartyLoaderFull/detail-4",
            "thumb": "http://ouya.cweiske.de/game-images/com.jackboxgames.JackboxPartyLoaderFull/detail-4-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.jackboxgames.JackboxPartyLoaderFull/detail-5",
            "thumb": "http://ouya.cweiske.de/game-images/com.jackboxgames.JackboxPartyLoaderFull/detail-5-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.jackboxgames.JackboxPartyLoaderFull/detail-6",
            "thumb": "http://ouya.cweiske.de/game-images/com.jackboxgames.JackboxPartyLoaderFull/detail-6-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.jackboxgames.JackboxPartyLoaderFull/detail-7",
            "thumb": "http://ouya.cweiske.de/game-images/com.jackboxgames.JackboxPartyLoaderFull/detail-7-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.jackboxgames.JackboxPartyLoaderFull/detail-8",
            "thumb": "http://ouya.cweiske.de/game-images/com.jackboxgames.JackboxPartyLoaderFull/detail-8-thumb"
        }
    ],
    "developer": {
        "uuid": null,
        "name": "Jackbox Games, Inc",
        "supportEmail": null,
        "supportPhone": null,
        "founder": false
    },
    "contentRating": "12+",
    "website": "www.jackboxgames.com",
    "firstPublishedAt": "2015-02-10T03:12:28Z",
    "inAppPurchases": false,
    "overview": "Released in April 2017 by Jackbox Games, Inc.",
    "premium": true,
    "rating": {
        "likeCount": 0,
        "average": 4.77,
        "count": 60
    },
    "products": [
        {
            "promoted": true,
            "identifier": "JackBoxPartyPack_License_Full_Upgrade",
            "name": "The Jackbox Party Pack",
            "description": "Includes all 5 games!",
            "localPrice": 24.99,
            "originalPrice": 24.99,
            "currency": "USD"
        }
    ]
}

=== ouya-saviors/ouya-game-data/gamestick/com.retrobomb.expendablerearmed.launcher.json
{
    "packageName": "com.retrobomb.expendablerearmed.launcher",
    "title": "Expendable Rearmed (Launcher)",
    "description": "AD 2463. For the last 500 years, among the bleak and barren worlds that exist in deep space, mankind has expanded its horizons. \r\n\r\nThe most suitable planets and moons near Earth have been terraformed, turning the once-inhospitable wastelands into habitable places. \r\n\r\nDeeper and deeper into the universe mankind spread itself, until only a mere handful of humans would or could survive the journey. ",
    "players": [
        1
    ],
    "genres": [
        "FPS/Shooter",
        "Launcher",
        "PlayJam GameStick"
    ],
    "releases": [
        {
            "name": "1.0",
            "versionCode": 1,
            "uuid": "54281482-1b9d-4683-a2ae-47413a7954cc",
            "date": "2025-11-12T17:14:16Z",
            "url": "http://ouya.cweiske.de/apks/gamestick/com.retrobomb.expendablerearmed/com.retrobomb.expendablerearmed.launcher-1.apk",
            "size": 131548,
            "md5sum": "14a33fcff6b117547dbab16931b6e4e5",
            "cert_fingerprint": "A3:81:0C:7A:E7:20:11:83:33:F6:8C:55:F4:9C:D4:14:5F:D4:A0:2E:C0:11:27:F8:CC:62:56:D6:A5:07:F4:1A",
            "cert_subject": "C=AT, OU=CEO, CN=Andreas St."
        }
    ],
    "discover": "http://ouya.cweiske.de/apks/gamestick/com.retrobomb.expendablerearmed/discover",
    "media": [
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/apks/gamestick/com.retrobomb.expendablerearmed/screen1.jpg"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/apks/gamestick/com.retrobomb.expendablerearmed/screen2.jpg"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/apks/gamestick/com.retrobomb.expendablerearmed/screen3.jpg"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/apks/gamestick/com.retrobomb.expendablerearmed/screen4.jpg"
        }
    ],
    "developer": {
        "name": "Retrobomb"
    },
    "contentRating": "12+",
    "website": null,
    "firstPublishedAt": "2012-12-20",
    "inAppPurchases": false,
    "premium": true,
    "relationships": {
        "original": "com.retrobomb.expendablerearmed"
    }
}

=== ouya-saviors/ouya-game-data/gamestick/com.ifightbears.fistofawesome.json
{
    "packageName": "com.ifightbears.fistofawesome",
    "title": "Fist of Awesome",
    "description": "Have you ever wanted to punch a bear IN THE MOUTH?\r\n\r\nWhen Tim Burr's family disappeared and his house spontaneously burst into flames he thought his day was as about bad as it could get. That's when his hand became self-aware and broke the horrific news that the world was now ruled by bears.\r\n\r\nJoin Tim as he embarks on an epic battle across time and space. It's a bit like Quantum Leap but with more bears and lumberjacks.",
    "players": [
        1
    ],
    "genres": [
        "Fight!",
        "PlayJam GameStick"
    ],
    "releases": [
        {
            "name": "1.1",
            "versionCode": 1,
            "uuid": "fa2ba3eb-0854-4e5f-ad95-93f348711c9e",
            "date": "2025-07-20T13:41:06Z",
            "url": "http://gamestick.cweiske.de/archive/gamestick_com.ifightbears.fistofawesome/Fist%20of%20Awesome_1.1_com.ifightbears.fistofawesome.apk",
            "size": 48829436,
            "md5sum": "1ab7f8ca051be7b724916f8a780c6529",
            "cert_fingerprint": "0E:DA:23:A7:98:10:F2:23:87:48:04:40:3E:EB:23:04:30:25:A4:F2:E2:71:79:EA:6A:A4:2F:B9:BF:64:AD:96",
            "cert_subject": "L=London, O=I Fight Bears, CN=Nicoll Hunt"
        }
    ],
    "discover": "http://ouya.cweiske.de/apks/gamestick/com.ifightbears.fistofawesome/discover",
    "media": [
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/apks/gamestick/com.ifightbears.fistofawesome/screen1.jpg"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/apks/gamestick/com.ifightbears.fistofawesome/screen2.jpg"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/apks/gamestick/com.ifightbears.fistofawesome/screen3.jpg"
        }
    ],
    "developer": {
        "name": "ifightbears"
    },
    "contentRating": "12+",
    "website": null,
    "firstPublishedAt": "2013-10-09",
    "inAppPurchases": false,
    "premium": true,
    "relationships": {
        "launcher": "com.ifightbears.fistofawesome.launcher"
    }
}

=== ouya-saviors/ouya-game-data/classic/com.epsilonstudios.FarrahRogueZH.json
{
    "packageName": "com.epsilonstudios.FarrahRogueZH",
    "title": "Farrah Rogue - Zero Hour",
    "description": "Farrah Rogue is a fast paced FPS couch multiplayer game. Get your friends together and kick some butt! This is still a Developer preview, there are rough edges. Weâ€™re working hard on new features and content. Please support us by joining our facebook page, and commenting on our ouyaforum.com thread. Thanks!\r\n\r\n-4 levels\r\n-Deathmatch (2-4 players)\r\n-Break the targets (single player)\r\n-Ship deathmatch (2-4players) **Developer preview**",
    "players": [
        1
    ],
    "genres": [
        "FPS/Shooter",
        "Multiplayer"
    ],
    "releases": [
        {
            "name": "1.0",
            "versionCode": 0,
            "uuid": "ba6c711e-a5f5-4fad-abac-c8fcbcd9d2c3",
            "date": "2014-06-26T21:27:10Z",
            "url": "https://archive.org/download/ouya_com.epsilonstudios.FarrahRogueZH_1.0/Farrah%20Rogue%20-%20Zero%20Hour_1.0_com.epsilonstudios.FarrahRogueZH.apk",
            "size": 217399240,
            "md5sum": "207bab01dffb229683f1ac45767e02a2",
            "publicSize": 460784,
            "nativeSize": 195984
        }
    ],
    "discover": "http://ouya.cweiske.de/game-images/com.epsilonstudios.FarrahRogueZH/discover",
    "media": [
        {
            "type": "video",
            "url": "https://vimeo.com/99194248"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.epsilonstudios.FarrahRogueZH/detail-1",
            "thumb": "http://ouya.cweiske.de/game-images/com.epsilonstudios.FarrahRogueZH/detail-1-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.epsilonstudios.FarrahRogueZH/detail-2",
            "thumb": "http://ouya.cweiske.de/game-images/com.epsilonstudios.FarrahRogueZH/detail-2-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.epsilonstudios.FarrahRogueZH/detail-3",
            "thumb": "http://ouya.cweiske.de/game-images/com.epsilonstudios.FarrahRogueZH/detail-3-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.epsilonstudios.FarrahRogueZH/detail-4",
            "thumb": "http://ouya.cweiske.de/game-images/com.epsilonstudios.FarrahRogueZH/detail-4-thumb"
        }
    ],
    "developer": {
        "uuid": null,
        "name": "Epsilon Studios",
        "supportEmail": "jguard@epsilonstudios.com",
        "supportPhone": null,
        "founder": false
    },
    "contentRating": "9+",
    "website": "www.epsilonstudios.com",
    "firstPublishedAt": "2014-05-27T07:11:24Z",
    "inAppPurchases": false,
    "overview": "Released in June 2014 by Epsilon Studios.",
    "premium": false,
    "rating": {
        "likeCount": 0,
        "average": 3.89,
        "count": 308
    }
}
